# Generated by Django 3.2.3 on 2021-07-13 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0005_alter_userprofile_tree_planting_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=60)),
                ('post_content', models.CharField(max_length=240)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='user_profiles.userprofile')),
            ],
        ),
    ]
