# Generated by Django 3.2.3 on 2021-07-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresspost',
            name='post_content',
            field=models.CharField(max_length=2000),
        ),
    ]
