# Generated by Django 3.2.3 on 2021-07-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_alter_userprofile_tree_planting_contribution'),
        ('blog', '0002_alter_progresspost_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresspost',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='user_profiles.userprofile'),
        ),
    ]
