# Generated by Django 3.2.3 on 2021-07-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_progresspost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresspost',
            name='post_content',
            field=models.TextField(max_length=2000),
        ),
    ]
