# Generated by Django 3.2.3 on 2021-07-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_userprofile_default_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_phone_number',
        ),
    ]
