# Generated by Django 3.2.3 on 2021-07-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_remove_userprofile_default_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tree_planting_contribution',
            field=models.IntegerField(default=0.0),
        ),
    ]
