# Generated by Django 3.2.3 on 2021-07-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_userprofile_tree_planting_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tree_planting_contribution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
